import type { SiteCopy } from "./types";

export const en: SiteCopy = {
  locale: "en",
  metadata: {
    title: "YAMI Design System",
    description: "Tokens, foundations, bilingual content, and verification workflows for YAMI.",
  },
  nav: { home: "Home", docs: "Docs", blog: "Blog", label: "YAMI documentation navigation" },
  utilities: {
    search: "Search",
    searchPlaceholder: "Search Docs and Blog",
    searchHint: "Enter a keyword. Use the arrow keys to select a result.",
    searchNavigate: "Navigate",
    searchSelect: "Select",
    noResults: "No results found. Try a different keyword.",
    menu: "Menu",
    close: "Close",
    language: "中文",
    lightMode: "Light",
    darkMode: "Dark",
    theme: "Theme",
    storybook: "Storybook",
    github: "GitHub",
  },
  home: {
    title: "YAMI DESIGN SYSTEM",
    description:
      "A design system agents can use directly, unifying design standards, interface components, and product copy into a product-building foundation they can understand, use, and validate.",
    primaryAction: "Start Building",
    secondaryAction: "Browse Components",
    status: "Currently in Alpha · Built with React 19 and TypeScript",
    previewTitle: "Real components. One rule set.",
    previewDescription: "The examples below use public YAMI components and semantic tokens directly.",
    capabilitiesTitle: "Start with rules.\nCompose for context.\nShip with confidence.",
    capabilitiesDescription: "YAMI keeps brand standards, interface components, and delivery checks connected to one source, reducing repeated decisions across design, engineering, and agents.",
    capabilities: [
      { title: "One visual language", description: "Explore color, typography, layout, and responsive guidelines to keep visual standards consistent across pages." },
      { title: "Reuse components. Focus on the product.", description: "Find components and page examples in Storybook. Review their usage, states, and interactions before choosing what to reuse." },
      { title: "Light and dark", description: "Components consume theme aliases automatically without adding a dark prop." },
      { title: "Give agents clear rules", description: "Choose a component or page task, then prepare references, prompts, and acceptance criteria so agents can start with clear requirements." },
    ],
    foundationsTitle: "Start with the foundations",
    foundationsDescription: "Learn the visual grammar before composing pages and product workflows.",
    latestTitle: "Latest from the Blog",
    latestDescription: "Read the design decisions, bilingual methods, and verification practices behind YAMI.",
    docsFeatureTitle: "Documentation for designers, engineers, and agents",
    docsFeatureDescription: "Find answers through one information architecture, from getting started and brand principles to tokens, accessibility, and collaboration workflows.",
    foundationsAction: "Explore Foundations",
    agentAction: "Learn the Workflow",
    docsAction: "Browse Docs",
    aboutTitle: "Shared standards, from design to code",
    aboutDescription: "Designers, developers, and agents share guidelines and components, keeping the focus on the product.",
    aboutActions: ["View design standards", "View components and pages", "Start creating with AI"],
    latestAction: "View All Posts",
    discoverTitle: "Discover the full YAMI Design System",
    discoverDescription: "Understand the rules in Docs, inspect components in Storybook, and build with the same semantic tokens.",
    validationLabels: ["Token inventory", "Bilingual content parity", "Build and interaction checks"],
  },
  docs: {
    label: "YAMI Docs",
    menu: "Docs Menu",
    onThisPage: "On This Page",
    updated: "Updated",
    previous: "Previous",
    next: "Next",
    groups: { start: "Use the library", ai: "Create with AI", collaboration: "Team collaboration", resources: "Resources and help" },
    resources: { components: "Browse components", foundations: "Design standards", pages: "Page examples" },
  },
  blog: {
    title: "Blog",
    description: "Release notes, design methods, and engineering practices from the YAMI Design System.",
    all: "All",
    categories: { update: "Update", design: "Design", engineering: "Engineering" },
    empty: "No articles yet. Explore another category.",
    readingTime: (minutes) => `${minutes} min read`,
    related: "Related Docs",
    previous: "Previous",
    next: "Next",
  },
  footer: {
    description: "YAMI connects brand standards, component implementation, and verifiable delivery workflows.",
    resources: "Resources",
    legal: "Release Note",
    version: "Version",
    license: "Repository license not declared",
    rights: "Public access does not grant redistribution rights for fonts, brand marks, or imagery.",
  },
  notFound: {
    title: "Page Not Found",
    description: "The link may have changed, or the content has not been published.",
    action: "Back to Home",
  },
};
