import type { SiteCopy } from "./types";

export const zh: SiteCopy = {
  locale: "zh",
  metadata: {
    title: "YAMI 设计系统",
    description: "YAMI 设计系统的 Token、基础规范、双语内容和验证工作流。",
  },
  nav: { home: "首页", docs: "文档", blog: "文章", label: "YAMI 文档站导航" },
  utilities: {
    search: "搜索",
    searchPlaceholder: "搜索文档和 Blog",
    searchHint: "输入关键词，使用方向键选择结果。",
    searchNavigate: "导航",
    searchSelect: "选择",
    noResults: "未找到结果。请更换关键词。",
    menu: "菜单",
    close: "关闭",
    language: "English",
    lightMode: "浅色",
    darkMode: "深色",
    theme: "主题",
    storybook: "Storybook",
    github: "GitHub",
  },
  home: {
    title: "YAMI DESIGN SYSTEM",
    description:
      "一个可直接供 Agent 使用的设计系统，将设计规范、界面组件与文案内容统一为 Agent 可理解、可调用、可检查的产品构建基础。",
    primaryAction: "开始构建",
    secondaryAction: "浏览组件",
    status: "当前为 Alpha · 基于 React 19 和 TypeScript",
    previewTitle: "真实组件，同一套规则",
    previewDescription: "下方示例直接使用 YAMI 公共组件和语义 Token。",
    capabilitiesTitle: "从规范开始。\n按场景组合。\n更放心交付。",
    capabilitiesDescription: "YAMI 让品牌规范、界面组件与交付检查共享同一套来源，减少设计、开发与 Agent 之间的重复判断。",
    capabilities: [
      { title: "统一视觉语言", description: "用同一套 Token 管理颜色、字体、间距与状态，让不同页面保持一致。" },
      { title: "复用组件，专注产品", description: "从按钮到页面模块，复用已有样式与交互，把时间留给具体的产品需求。" },
      { title: "亮暗模式", description: "组件自动消费主题语义别名，不需要新增 dark 属性。" },
      { title: "让 Agent 按规范构建", description: "提供明确的设计规则、可复用组件与检查工具，让 Agent 有据可循。" },
    ],
    foundationsTitle: "从基础规范开始",
    foundationsDescription: "先理解系统的视觉语法，再组合页面和业务流程。",
    latestTitle: "最新文章",
    latestDescription: "了解 YAMI 的设计决策、双语方法与验证流程。",
    docsFeatureTitle: "为设计、开发与 Agent 准备的文档",
    docsFeatureDescription: "从快速开始到品牌原则、Token、无障碍和协作流程，按同一套信息架构查找答案。",
    foundationsAction: "查看基础规范",
    agentAction: "了解协作流程",
    docsAction: "浏览文档",
    aboutTitle: "从设计到代码，共用一套标准",
    aboutDescription: "让设计师、开发者与 Agent 共享规范和组件，把精力放在产品本身。",
    learnMore: "了解更多",
    latestAction: "查看全部",
    discoverTitle: "探索完整的 YAMI 设计系统",
    discoverDescription: "从文档理解规则，在 Storybook 检查组件，并用同一套 Token 完成实现。",
    validationLabels: ["Token 清单", "双语内容配对", "构建与交互检查"],
  },
  docs: {
    label: "YAMI 文档",
    menu: "文档目录",
    onThisPage: "本页内容",
    updated: "更新于",
    previous: "上一篇",
    next: "下一篇",
    groups: { start: "使用组件库", ai: "用 AI 搭建页面", collaboration: "多人协作", maintenance: "扩展与维护", resources: "资源与帮助" },
    resources: { components: "浏览组件", foundations: "查看设计规范", pages: "查看页面示例" },
  },
  blog: {
    title: "Blog",
    description: "记录 YAMI 设计系统的版本、设计方法和工程实践。",
    all: "全部",
    categories: { update: "更新", design: "设计", engineering: "工程" },
    readingTime: (minutes) => `${minutes} 分钟阅读`,
    related: "关联文档",
    previous: "上一篇",
    next: "下一篇",
  },
  footer: {
    description: "YAMI 设计系统连接品牌规范、组件实现与可验证的交付流程。",
    resources: "资源",
    legal: "发布说明",
    version: "版本",
    license: "仓库许可证未声明",
    rights: "公开访问不代表字体、品牌标识或图片素材已获得再分发授权。",
  },
  notFound: {
    title: "页面不存在",
    description: "链接可能已变更，或内容尚未发布。",
    action: "返回首页",
  },
};
