import type { FooterProps, ProductListItem } from "@yami/design-system";
import {
  createFooterAppLinks,
  createFooterColumns,
  createFooterLegalLinks,
  createFooterPaymentMarks,
  createFooterSocialLinks,
  footerCopy,
} from "@yami/design-system/components/Footer/fixtures";

import { createStorefrontHeader } from "../storefront-header.fixture";

import type { ProductDetailPageProps } from "./ProductDetailPage.types";

const productImages = [
  ["front", "22f1eabda8bc0200d050ebcb1ebdb469", "Torriden Dive In Low Molecule Hyaluronic Acid Mask box, front view"],
  ["packaging", "c635ba73e529d262e7b2e25d3a7fb89c", "Torriden Dive In mask packaging and individual sheet"],
  ["sheet", "f743668cac11a24b973ff93050844c06", "Torriden Dive In sheet mask texture detail"],
  ["benefits", "1923d15747c92c8d0654f5fa2126e8a0", "Torriden Dive In mask hydration benefits"],
  ["essence", "1e27d193f4e6419c5022dbcdb7cb6999", "Torriden Dive In mask essence and skin application"],
  ["routine", "40b6a28e72b49612936923948ae7953e", "Torriden Dive In mask skincare routine detail"],
] as const;

function image(hash: string) {
  return `https://cdn.yamibuy.net/item/${hash}_757x757.webp`;
}

function recommendation(
  id: string,
  hash: string,
  brand: string,
  title: string,
  priceCurrent: string,
  priceOriginal: string,
  ratingCount: string,
): ProductListItem {
  return {
    id,
    href: `#${id}`,
    image: image(hash),
    imageAlt: title,
    brand,
    brandHref: `#${brand.toLowerCase()}`,
    title,
    priceCurrent,
    priceOriginal,
    rating: 4.8,
    ratingCount,
    soldCount: "100+ sold",
    badges: [{ label: "Low Price", type: "low-price" }],
    addButtonAriaLabel: `Add ${title} to cart`,
  };
}

function createFooter(): FooterProps {
  const copy = footerCopy.en;
  return {
    ariaLabel: copy.ariaLabel,
    columns: createFooterColumns("en"),
    socialLinks: createFooterSocialLinks("en"),
    subscribe: {
      title: copy.subscribeTitle,
      label: copy.subscribeLabel,
      placeholder: copy.subscribePlaceholder,
      submitLabel: copy.subscribeSubmit,
    },
    appTitle: copy.appTitle,
    appLinks: createFooterAppLinks(),
    copyright: copy.copyright,
    legalLinks: createFooterLegalLinks("en"),
    paymentMarks: createFooterPaymentMarks(),
    imageLoading: "lazy",
  };
}

function createProductDetailHeader() {
  const header = createStorefrontHeader("en");
  return {
    ...header,
    imageLoadingStrategy: "windowed" as const,
  };
}

export function createProductDetailPageFixture(): ProductDetailPageProps {
  return {
    contentMaxWidth: 1920,
    header: createProductDetailHeader(),
    footer: createFooter(),
    breadcrumb: [
      { label: "Beauty", href: "#beauty" },
      { label: "Masks", href: "#masks" },
      { label: "Sheet Masks" },
    ],
    images: productImages.map(([id, hash, alt]) => ({
      id,
      src: image(hash),
      alt,
    })),
    brand: "Torriden",
    brandHref: "#torriden",
    title: "Dive In Low Molecule Hyaluronic Acid Mask, 0.91 fl oz 10pcs",
    ranking: "#3 Most Liked Masks",
    rating: 4.7,
    ratingCount: "10",
    soldCount: "400+ sold",
    priceCurrent: "$16.29",
    priceOriginal: "$20.99",
    discountLabel: "22% off",
    optionGroups: [
      {
        id: "mask-type",
        label: "Mask Type",
        value: "hyaluronic",
        options: [
          { label: "Pink Cellmazing Firming", value: "firming", unavailable: true },
          { label: "Hyaluronic", value: "hyaluronic" },
          { label: "Cica", value: "cica" },
        ],
      },
      {
        id: "packaging",
        label: "Standard Packaging",
        value: "10-sheets",
        options: [
          { label: "4 sheets/box", value: "4-sheets" },
          { label: "5 sheets", value: "5-sheets" },
          { label: "10 sheets", value: "10-sheets" },
          { label: "20 sheets", value: "20-sheets" },
          { label: "3 packs", value: "3-packs" },
        ],
      },
    ],
    bestBefore: "Sep 15, 2028",
    highlights: [
      "Contains a 5D hyaluronic acid complex designed for multi-layer hydration.",
      "Soft vegan cellulose sheets hold a full bottle of essence and conform closely to skin.",
      "The lightweight essence absorbs without a sticky finish, including on oily skin.",
      "Soothing ingredients support sensitive skin and help reduce post-use tightness.",
      "A 15-minute routine leaves skin feeling supple, dewy, and comfortably hydrated.",
    ],
    specifications: [
      { label: "Brand", value: "Torriden" },
      { label: "Brand origin", value: "Korea" },
      { label: "Net content", value: "1 box" },
      { label: "Mask type", value: "Hyaluronic" },
      { label: "Packaging", value: "10 sheets" },
    ],
    serviceDetailsHref: "#product-highlights",
    purchaseTags: ["Best Sellers", "New Arrivals", "Dryness", "Oily", "Dry"],
    recommendations: [
      recommendation("biodance-mask", "c8dcfa16d92b0def7c96453886efa36e", "BIODANCE", "Bio-Collagen Real Deep Mask, Hydrating and Firming, 4pcs", "$16.00", "$19.00", "41"),
      recommendation("mediheal-mask", "868c0f52ce4313e6e25590c6912b76be", "MEDIHEAL", "Essential Mask Madecassoside Soothing, 10 sheets", "$10.39", "$26.99", "22"),
      recommendation("abib-mask", "090012ed3cd043cc3ee4ed514a5d56a9", "Abib", "Mild Acidic pH Sheet Mask, 10 sheets", "$16.29", "$19.99", "18"),
      recommendation("torriden-cica", "571149d4d5b62b680da7db7c4cf4da19", "Torriden", "Balanceful Cica Mask, Soothing Care, 10 sheets", "$17.49", "$29.99", "12"),
      recommendation("jm-solution-mask", "676f94362d286f3b93d0d1dee0b31cb2", "JMsolution", "Active Jellyfish Vital Mask Prime, 10 sheets", "$8.09", "$17.50", "219"),
      recommendation("abib-glutathiosome-mask", "73b46a19a95b9d0ef8dc5f51f8e88d36", "Abib", "Mild Acidic pH Sheet Mask, Glutathiosome fit, 10 sheets/box", "$15.89", "$19.66", "70"),
      recommendation("dr-jart-vital-hydra-mask", "8b494fb3edce1e9f6a9ec9fa21e9bc1f", "Dr.Jart+", "Vital Hydra Solution Face Mask, 5 sheets/box × 3", "$19.99", "$35.97", "596"),
      recommendation("snp-birds-nest-mask", "fd8182dd56284740b83a16dcd23cbeeb", "SNP", "Bird’s Nest Aqua Ampoule Mask, 10 sheets", "$8.09", "$17.50", "219"),
    ],
    reviewSection: {
      title: "Reviews",
      reviewCount: 10,
      averageRating: 4.7,
      ratingDistribution: [
        { stars: 5, percentage: 80, count: 8 },
        { stars: 4, percentage: 10, count: 1 },
        { stars: 3, percentage: 10, count: 1 },
        { stars: 2, percentage: 0, count: 0 },
        { stars: 1, percentage: 0, count: 0 },
      ],
      reviews: [
        {
          id: "review-k-baby",
          rating: 5,
          reviewer: "K Baby",
          reviewedAt: "Dec 8, 2024",
          locale: "Reviewed in US",
          verifiedPurchase: true,
          currentItem: true,
          variant: "Mask Type: Hyaluronic · Packaging: 10 sheets",
          body: "Very hydrating and comfortable to use.",
          showOriginalHref: "#review-k-baby-original",
          helpfulCount: 2,
          commentCount: 0,
        },
        {
          id: "review-rain",
          rating: 5,
          reviewer: "Rain***",
          reviewedAt: "Mar 13, 2025",
          locale: "Reviewed in US",
          verifiedPurchase: true,
          currentItem: true,
          variant: "Mask Type: Hyaluronic · Packaging: 10 sheets",
          body: "A deeply moisturizing mask that leaves skin feeling soft.",
          showOriginalHref: "#review-rain-original",
          helpfulCount: 1,
          commentCount: 0,
        },
        {
          id: "review-daren",
          rating: 5,
          reviewer: "Daren***",
          reviewedAt: "Aug 3, 2026",
          locale: "Reviewed in US",
          verifiedPurchase: true,
          currentItem: true,
          variant: "Mask Type: Hyaluronic · Packaging: 10 sheets",
          body: "Noticeably moisturizing and comfortable to apply.",
          helpfulCount: 0,
          commentCount: 0,
          photos: [
            {
              src: image("f743668cac11a24b973ff93050844c06"),
              alt: "Torriden sheet mask texture shared with a review",
            },
          ],
        },
        {
          id: "review-sammi",
          rating: 5,
          reviewer: "SammiG107",
          reviewedAt: "Dec 22, 2025",
          locale: "Reviewed in US",
          verifiedPurchase: true,
          currentItem: true,
          variant: "Mask Type: Hyaluronic · Packaging: 10 sheets",
          body: "My skin felt more moisturized after use, and I would purchase it again.",
          helpfulCount: 0,
          commentCount: 0,
        },
        {
          id: "review-meencantachina",
          rating: 5,
          reviewer: "Meencantachina",
          reviewedAt: "Aug 24, 2025",
          locale: "Reviewed in US",
          verifiedPurchase: true,
          currentItem: true,
          variant: "Mask Type: Hyaluronic · Packaging: 10 sheets",
          body: "A simple routine with a strong hydrating effect.",
          helpfulCount: 0,
          commentCount: 0,
        },
        {
          id: "review-mujimuji",
          rating: 4,
          reviewer: "mujimuji",
          reviewedAt: "Mar 29, 2025",
          locale: "Reviewed in US",
          verifiedPurchase: true,
          currentItem: true,
          variant: "Mask Type: Hyaluronic · Packaging: 10 sheets",
          body: "Hydrating for dry, sensitive skin with a lightweight finish.",
          helpfulCount: 0,
          commentCount: 0,
        },
        {
          id: "review-dorothy",
          rating: 3,
          reviewer: "dorothyhaz",
          reviewedAt: "Sep 25, 2024",
          locale: "Reviewed in US",
          verifiedPurchase: true,
          currentItem: true,
          variant: "Mask Type: Hyaluronic · Packaging: 10 sheets",
          body: "A pleasant mask with a soft sheet and comfortable essence.",
          helpfulCount: 0,
          commentCount: 0,
        },
        {
          id: "review-tasha",
          rating: 5,
          reviewer: "tasha奶奶",
          reviewedAt: "Aug 13, 2022",
          locale: "Reviewed in US",
          verifiedPurchase: true,
          currentItem: true,
          variant: "Mask Type: Hyaluronic · Packaging: 10 sheets",
          body: "The sheet feels substantial and leaves skin moisturized without heaviness.",
          helpfulCount: 0,
          commentCount: 0,
        },
        {
          id: "review-biubiu",
          rating: 5,
          reviewer: "BiubiuJose",
          reviewedAt: "Jan 12, 2026",
          locale: "Reviewed in US",
          verifiedPurchase: true,
          currentItem: true,
          variant: "Mask Type: Hyaluronic · Packaging: 10 sheets",
          body: "A convenient moisturizing step with a comfortable, non-sticky finish.",
          helpfulCount: 3,
          commentCount: 0,
        },
        {
          id: "review-sky",
          rating: 5,
          reviewer: "skincarelover",
          reviewedAt: "Apr 7, 2025",
          locale: "Reviewed in US",
          verifiedPurchase: true,
          currentItem: true,
          variant: "Mask Type: Hyaluronic · Packaging: 10 sheets",
          body: "Soft, soothing, and easy to fit into a weekly hydration routine.",
          helpfulCount: 1,
          commentCount: 0,
        },
      ],
      copy: {
        reviewsLabel: "Reviews",
        writeReview: "Write a review",
        all: "All",
        purchased: "Purchased",
        photos: "Photos",
        sortBy: "Sort by",
        viewMore: "View more",
        verifiedPurchase: "Verified purchase",
        currentItem: "Current item",
        showOriginal: "Show original",
        helpful: "Helpful",
        comments: "Comments",
        noReviews: "No reviews match this filter.",
        stars: "Stars",
        resetFilter: "Show all reviews",
      },
      sortOptions: [
        { value: "default", label: "Default" },
        {
          value: "recent",
          label: "Most recent",
          compare: (left, right) =>
            Date.parse(String(right.reviewedAt ?? "")) -
            Date.parse(String(left.reviewedAt ?? "")),
        },
      ],
      initialVisibleCount: 6,
      viewMoreIncrement: 3,
    },
    brandSection: {
      title: "Torriden",
      aboutLabel: "About the brand",
      description:
        "Torriden creates clean, vegan, and cruelty-free formulas focused on effective hydration. Its signature 5D-Complex low molecular hyaluronic acid supports layered moisture without a sticky finish.",
      viewAllHref: "#torriden-products",
      viewAllLabel: "View all",
      previousLabel: "Previous Torriden products",
      nextLabel: "Next Torriden products",
      products: [
        recommendation("torriden-serum", "db87c5c18e08c04278e4ea52fca49baa", "Torriden", "Dive In Low Molecule Hyaluronic Acid Serum, 1.7 fl oz", "$17.99", "$24.00", "19"),
        recommendation("torriden-cream", "3ccf61fd74fd43320d647a1b8779a978", "Torriden", "Dive In Low Molecular Hyaluronic Acid Soothing Cream, 3.38 fl oz", "$17.19", "$21.00", "11"),
        recommendation("torriden-pads", "d0e2ff743dbd793ce3bde737ca0d5915", "Torriden", "Dive In Low Molecular Hyaluronic Acid Multi Pad, 80pcs", "$16.59", "$26.00", "10"),
        recommendation("torriden-sun-serum", "7ff5c4a9f6e222d2f1339524bed0bd61", "Torriden", "Dive In Watery Sun Serum, 1.69 fl oz", "$14.99", "$29.00", "8"),
        recommendation("torriden-mask-value", "dffa7586c7799b674cc7a2024fba1bf4", "Torriden", "Dive In Low Molecule Hyaluronic Acid Mask, 20pcs", "$32.99", "$41.98", "2"),
        recommendation("torriden-cica-mask", "c89197762808c1b9d132550a33943908", "Torriden", "Balanceful Cica Facial Sheet Masks, 10pcs", "$17.29", "$29.99", "3"),
        recommendation("torriden-night-set", "f836e9292cf3db92609ae245f0eea8d3", "Torriden", "DIVE IN Low-Molecular Emergency Night Skincare Set", "$29.99", "$57.00", "1"),
        recommendation("torriden-toner", "a3c484049ff6976250c79c2bc9f5c65d", "Torriden", "Dive In Vegan Low Molecular Hyaluronic Acid Toner, 10.14 fl oz", "$15.49", "$19.99", "1"),
      ],
    },
    copy: {
      galleryLabel: "Product image gallery",
      thumbnailsLabel: "Choose a product image",
      previousImage: "Previous product image",
      nextImage: "Next product image",
      ratingLabel: "Rating",
      writeReview: "Write a review",
      bestBefore: "Best before",
      productHighlights: "Product highlights",
      specifications: "Specifications",
      disclaimer: "Disclaimer",
      disclaimerBody: "Product packaging, specifications, and price may change without notice. Always read the product label, warnings, and directions before use.",
      addToFavorites: "Add to favorites",
      share: "Share product",
      shareWeibo: "Share on Weibo",
      shareFacebook: "Share on Facebook",
      shareEmail: "Share by email",
      shareWechat: "Share on WeChat",
      quantity: "Quantity",
      decreaseQuantity: "Decrease quantity",
      increaseQuantity: "Increase quantity",
      addToCart: "Add to Cart",
      seller: "Sold by",
      shipTo: "Ship to",
      deliveryEstimate: "Get it tomorrow, Aug 21, if you order before 1:30 AM tomorrow.",
      serviceGuarantees: ["Free shipping over $49", "Easy returns", "Ships from the United States"],
      viewDetails: "View details",
      tags: "Tags",
      showAllTags: "Show all",
      showFewerTags: "Show fewer",
      recommendations: "Recommendations based on this item",
      viewAll: "View all",
    },
  };
}
